Full refactoring, single dumpjobs working (without full logging).

diff --git a/bin/pgsnap_clean b/bin/pgsnap_clean
--- a/bin/pgsnap_clean
+++ b/bin/pgsnap_clean
@@ -1,3 +1,44 @@
 #!/bin/bash
 
+# ======================================
+# Initialization
+# ======================================
+
+# Get the script directory (must do this first)
+SOURCE="${BASH_SOURCE[0]}"
+while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
+  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
+  SOURCE="$(readlink "$SOURCE")"
+  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
+done
+SCRIPTPATH="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
+
+# Catalog database needed?
+PGSCDB_REQUIRED=NO
+
+# Load functions, will also perform initialization operations
+. ${SCRIPTPATH}/pgsnap_lib
+
+# =======================================
+# MAIN
+# =======================================
+
+# Clean up temp files from previously running jobs (unclean exit, or just because we have to)
+find ${TEMPDIR} -type f -mtime 1 > ${TEMPDIR}/clean_running.temp
+find ${TEMPDIR} -type f -name '*.running' >> ${TEMPDIR}/clean_running.temp
+find ${DUMPSNAP} -type f -maxdepth 2 -name '*.running' >> ${TEMPDIR}/clean_running.temp
+while read line; do
+  chkpid=$(echo `basename $line` | cut -d '.' -f 1)
+  ps -p $chkpid > /dev/null
+  if [ "$?" == "1" ]; then
+    rm $line
+  fi
+done < ${TEMPDIR}/clean_running.temp
+rm ${TEMPDIR}/clean_running.temp
+
+
+# Retention policy-cleaning...
+
+# TBD!
+
 exit 0
diff --git a/bin/pgsnap_lib b/bin/pgsnap_lib
--- a/bin/pgsnap_lib
+++ b/bin/pgsnap_lib
@@ -81,7 +81,7 @@ function getinstancestatus {
 function getworkerstatus {
   # Init/activate by default
   if [ ! -e ${ROOTDIR}/status ]; then
-    echo "ACTIVE" > "${ROOTDIR}/status" 
+    echo "ACTIVE" > ${ROOTDIR}/status 
   fi
   # Get data from server
   local workerstatus="UNKNOWN"
@@ -91,7 +91,7 @@ function getworkerstatus {
   else
     # compare with cached version, if different: store the current value
     if [ "${workerstatus}" != "`cat ${ROOTDIR}/status`" ]; then
-      echo "${workerstatus}" > "${ROOTDIR}/status"
+      echo "${workerstatus}" > ${ROOTDIR}/status
       snaplog "INFO" "worker status changed to: ${workerstatus}"
     fi
   fi
@@ -146,6 +146,14 @@ function getdbsize {
   echo "${dbsize}"
 }
 
+# Mark a single run job as started in the database
+# $1 jobid
+# $2 job class/type [DUMP|RESTORE]
+function setsinglerunstarted {
+  local sql="SELECT put_singlerun($1, '$2')"
+  ${PGSCBIN}/psql ${PGSCHOST} -p ${PGSCPORT} -U ${PGSCUSER} --dbname=${PGSCDB} -c "$sql" > /dev/null
+}
+
 # =====================================
 # Init actions
 # =====================================
@@ -161,6 +169,16 @@ if [ -e ${CONFIGFILE} ]; then
   . ${CONFIGFILE}
 else
   echo "pgsnapman config file not found: "${CONFIGFILE}
+  exit 1
+fi
+
+# Test for existing root dir
+if [ "`echo "${ROOTDIR}" | grep ' '`" != "" ]; then
+  echo "ERROR PgSnapMan root name contains spaces [${ROOTDIR}]"
+  exit 1
+fi
+if [ ! -d "${ROOTDIR}" ]; then
+  echo "ERROR PgSnapMan root directory does not exist [${ROOTDIR}]"
   exit 1
 fi
 
